### ISSUE TITLE
Validate ip address

### ISSUE THREAD

**Issue by edvm** [fmorisan/hyperboria-dns#1]
If we have test data saved on the blockchain, code will raise an exception:
```Exception happened during processing of request from ('127.0.0.1', 53650)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 651, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "/home/edvm/.local/share/virtualenvs/hyperboria-dns-7zAmtXLj/lib/python3.6/site-packages/dnslib/server.py", line 144, in handle
    rdata = self.get_reply(data)
  File "/home/edvm/.local/share/virtualenvs/hyperboria-dns-7zAmtXLj/lib/python3.6/site-packages/dnslib/server.py", line 161, in get_reply
    reply = resolver.resolve(request,self)
  File "ethdns.py", line 56, in resolve
    reply.add_answer(RR(qname, QTYPE.AAAA, ttl=1, rdata=AAAA(ip)))
  File "/home/edvm/.local/share/virtualenvs/hyperboria-dns-7zAmtXLj/lib/python3.6/site-packages/dnslib/dns.py", line 1186, in __init__
    self.data = _parse_ipv6(data)
  File "/home/edvm/.local/share/virtualenvs/hyperboria-dns-7zAmtXLj/lib/python3.6/site-packages/dnslib/dns.py", line 1119, in _parse_ipv6
    l_groups = list(chain(*[divmod(int(x,16),256) for x in l.split(":") if x]))
  File "/home/edvm/.local/share/virtualenvs/hyperboria-dns-7zAmtXLj/lib/python3.6/site-packages/dnslib/dns.py", line 1119, in <listcomp>
    l_groups = list(chain(*[divmod(int(x,16),256) for x in l.split(":") if x]))
ValueError: invalid literal for int() with base 16: 'test'
```
Quickfix:
Just use ipaddress to validate received ip address. I'll do it and send a PR :+1:

**Comment by fmorisan** [comment]
Merged and closing.
